### ISSUE TITLE
Country

### ISSUE THREAD

**Issue by mqnabeel** [NishanthMuruganantham/ndtv-api#2]
Is their any settings for country tryping to change country

**Comment by NishanthMuruganantham** [comment]
Hi @mqnabeel,

Thanks for your comment! Sorry for the delay. 

There are no settings currently to get the Country-wise news. The official NDTV website itself, does not have that category whereas they are having the category World News, which brings News across the countries. Since this API has been built on top of that, it also doesn't have any option to give the country-wise news. But, you can get world News.

Hope it helps!

**Comment by satyam0337** [comment]
hi bro 
ndtv ka api kaise use kare

**Comment by satyam0337** [comment]
please bro urgent hai whatspp number 7519350908
please btana bro

**Comment by mdharis107** [comment]
Bro is there an option for listing only limited items in one particular page....

**Comment by NishanthMuruganantham** [comment]
> please bro urgent hai whatspp number 7519350908 please btana bro



> 



> hi bro ndtv ka api kaise use kare

Hi @satyam0337 , sorry for the late reply. Just got to see your comment. You can use this API with any of your front end sites for testing purposes say if you're building a News App or something similar to that. You can just follow the instructions using Postman where you can get the data from API

**Comment by NishanthMuruganantham** [comment]
> Bro is there an option for listing only limited items in one particular page.... if there please give an example with API bro... really need Bro... But Anyway thank You for the API Bro...

sorry @mdharis107 bro, currently there's no future to limit the number of results. But, if you're using this as a source for any of your front end applications (Web/ Mobile App), you can limit the data with the help of pagination or Javascript/Ajax loader
